### ISSUE TITLE
[Feature Request] Option to dedent code blocks

### ISSUE THREAD

**Issue by Devessier** [temporalio/snipsync#40]
### Is your feature request related to a problem? Please describe.

Sometimes I want to embed code that is indented. The problem is that the code remains indented once embedded and it is not really pretty.

As an example, I wanted to embed a tag from a HTML file, the tag being indented: https://github.com/Devessier/portfolio/blob/c4712384ca203a1473801636356070415cffa47c/src/app.html#L8-L10.

I want to keep the code indented where it is defined, but I want to have it dedented once embedded.

### Describe the solution you'd like

I'm sorry if there is already a solution to this issue. If there is one, I did not find it.

I would suggest an option to automatically dedent code snippets. There is currently `enable_source_link` and `enable_code_block` options, that are available at the global level and at the level of one snippet.

There could also be an option like `enable_code_dedent`, or any better name, that could use [dedent library](https://github.com/dmnd/dedent) to dedent the code snippet.

### Additional context

I am sorry if my suggestion is irrelevant or if you don't think it belongs to the scope of the project.

On the other hand, I can suggest an implementation.

Have a nice day!

**Comment by lorensr** [comment]
I'd like this as well. Currently when I have:

![image](https://user-images.githubusercontent.com/251288/163727421-d9e70a89-0635-49b5-a197-5d1a19910968.png)

https://github.com/temporalio/samples-typescript/blob/main/ejson/src/worker.ts

I see:

![image](https://user-images.githubusercontent.com/251288/163727409-074767c4-d68c-4dd1-b19c-069693b54870.png)

https://docs.temporal.io/docs/typescript/data-converters/#custom-implementation
