### ISSUE TITLE
[Bug] Default URL

### ISSUE THREAD

**Issue by rachfop** [temporalio/snipsync#62]
### What are you really trying to do?

I believe there was a push to use the `main` branch in all temporal owned repos.
The default URL should be to use `main` and not `master`.

### Describe the bug

Current snippets point to `master` in the URL.
GitHub redirects to main automatically, but maybe we should fix it in the code.
### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by flossypurse** [comment]
Pretty sure this is resolved now - default has been updated to main.
